// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/_app.tsx';
import * as $1 from './routes/index.tsx';
import * as $2 from './routes/md.tsx';
import * as $3 from './routes/test/button.tsx';
import * as $4 from './routes/test/gradient.tsx';
import * as $5 from './routes/test/input.tsx';
import * as $$0 from './islands/Island.tsx';

const manifest = {
  routes: {
    './routes/_app.tsx': $0,
    './routes/index.tsx': $1,
    './routes/md.tsx': $2,
    './routes/test/button.tsx': $3,
    './routes/test/gradient.tsx': $4,
    './routes/test/input.tsx': $5,
  },
  islands: {
    './islands/Island.tsx': $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
